default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5

development:
  <<: *default
  host: localhost
  database: rails_development
  username: rails_app
  password: rails_app

test:
  <<: *default
  host: localhost
  database: rails_development
  username: rails_app
  password: rails_app

production:
  <<: *default
  database: rails_production
  url: mysql2://<%= ENV["DB_USER_NAME"] %>:<%= ENV["DB_PASS"] %>@db:3306
