default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV["DB_USER_NAME"] %>
  password: <%= ENV["DB_PASS"] %>

development:
  <<: *default
  host: localhost
  database: rails_development

test:
  <<: *default
  host: localhost
  database: rails_development


production:
  <<: *default
  host: db
  database: rails_production
