default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost
  username: rails_app
  password: rails_app


development:
  <<: *default
  database: rails_development

test:
  <<: *default
  database: rails_test

production:
  <<: *default
  host: <%= ENV["DB_HOST"] %>
  database: rails_production
  username: <%= ENV["DB_USER_NAME"] %>
  password: <%= ENV["DB_PASS"] %>
